spring:
  profiles :
      active : true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: ${example.flyway.enabled}
    baseline-version: 1.0
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/dev
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

